'''
@Author: WANG Maonan
@Date: 2026-08-18
@Description: 解析 SUMO map.poly.xml —— **只有「带 poly」的输入模式会用到**.

poly 文件由 tshub.sumo_tools.osm_build 从 OSM 生成, 建筑轮廓与高度信息都自带,
不需要额外的高度表:
- parse_buildings   : 建筑轮廓 + 高度 (height / building:levels), 供 Blender 按真实轮廓挤出;
- parse_green_areas : 公园/林地等绿地轮廓, 供 scatter 在其中种树.

不带 poly 时这两样都没有, 建筑改由 scatter 沿街摆放装饰模型 (见 scatter.py).
'''
import re
import xml.etree.ElementTree as ET

# OSM 的数值字段很脏 ("12", "12.5 m", "40 ft"), 统一用它抓第一个数字
NUMBER_RE = re.compile(r"-?\d+(?:\.\d+)?")


def _parse_osm_number(value) -> float:
    """Read the first positive number from an OSM/SUMO param value.

    Handles common values such as ``"12"``, ``"12.5"``, ``"12 m"`` and
    ``"40 ft"``.  Compound values are intentionally reduced to the first number;
    source map data is noisy, and a stable approximate height is better than
    falling back to the generic default.
    """
    if value is None:
        return None
    text = str(value).strip().lower().replace(",", ".")
    match = NUMBER_RE.search(text)
    if not match:
        return None
    number = float(match.group(0))
    if number <= 0:
        return None
    if "ft" in text or "feet" in text:
        number *= 0.3048
    return number


def _poly_param_value(poly, keys):
    keys = set(keys)
    for param in poly.findall('param'):
        if param.get('key') in keys:
            return param.get('value')
    return None


def _poly_param_height(poly, level_height: float = 3.2):
    """Read height from params already preserved in map.poly.xml."""
    height = _parse_osm_number(_poly_param_value(poly, ('height', 'building:height')))
    if height is not None:
        return height

    levels = _parse_osm_number(_poly_param_value(poly, ('building:levels', 'levels')))
    if levels is not None:
        return levels * level_height
    return None


def parse_buildings(poly_xml: str, default_height: float = 12.0,
                    building_level_height: float = 3.2) -> list:
    """Read SUMO building polygons and attach a height for each footprint.

    Building info is self-contained in the SUMO ``map.poly.xml`` generated by
    ``tshub.sumo_tools.osm_build``.  Height priority:
    ``height`` / ``building:height`` params, then
    ``building:levels`` / ``levels`` params multiplied by ``building_level_height``,
    then ``default_height``.
    """
    tree = ET.parse(poly_xml)
    buildings = []
    for poly in tree.getroot().iter('poly'):
        if poly.get('type') != 'building':
            continue
        pts = poly.get('shape', '').split()
        footprint = [[float(c) for c in p.split(',')[:2]] for p in pts if ',' in p]
        if len(footprint) < 3:
            continue
        height = _poly_param_height(poly, building_level_height)
        if height is None:
            height = default_height
        buildings.append({'footprint': footprint, 'height': float(height)})
    return buildings


# OSM/polyconvert poly types that are vegetated ground (trees scattered inside).
GREEN_TYPES = {
    'natural', 'forest', 'wood', 'grass', 'meadow', 'scrub', 'park', 'leisure',
    'garden', 'farmland', 'orchard', 'greenfield', 'recreation_ground',
}


def parse_green_areas(poly_xml: str) -> list:
    """Read SUMO green polygons (parks/forests/natural) as footprints for trees."""
    tree = ET.parse(poly_xml)
    greens = []
    for poly in tree.getroot().iter('poly'):
        poly_type = (poly.get('type') or '').split('.')[0]
        if poly_type not in GREEN_TYPES:
            continue
        pts = poly.get('shape', '').split()
        ring = [[float(c) for c in p.split(',')[:2]] for p in pts if ',' in p]
        if len(ring) >= 3:
            greens.append(ring)
    return greens
